# Generated by Django 5.0.7 on 2024-08-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='recipe_fk',
        ),
        migrations.AddField(
            model_name='recipe',
            name='steps',
            field=models.ManyToManyField(related_name='steps_recipe', to='kitchen_app.step'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipe', to='kitchen_app.food'),
        ),
    ]
