# Generated by Django 5.0.7 on 2024-08-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen_app', '0002_remove_step_recipe_fk_recipe_steps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='time_to_prepare',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
