# Generated by Django 5.0.7 on 2024-08-08 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen_app', '0003_recipe_time_to_prepare'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 8, 12, 56, 33, 590467, tzinfo=datetime.timezone.utc)),
        ),
    ]
